/**
 * Image generation with automatic fallback between providers.
 *
 * Each provider is tried in order (IMAGE_PROVIDERS secret, default
 * "stability,cloudflare,huggingface"); providers without credentials are
 * skipped. Any failure (quota, 402/429/503, timeout, refusal…) moves on to the
 * next one; only when all fail does the Studio receive one clear error listing
 * every reason.
 */
import { HttpError } from './http.ts';
import { cloudflareProvider } from './image-providers/cloudflare.ts';
import { huggingFaceProvider } from './image-providers/huggingface.ts';
import { stabilityProvider } from './image-providers/stability.ts';
import {
  ImageProviderError,
  type GeneratedImage,
  type ImageBrief,
  type ImageContentType,
  type ImageProvider,
} from './image-providers/common.ts';

export type { AspectRatio, GeneratedImage, ImageBrief } from './image-providers/common.ts';

const PROVIDERS: Record<string, ImageProvider> = {
  stability: stabilityProvider,
  cloudflare: cloudflareProvider,
  huggingface: huggingFaceProvider,
};

function providerChain(): ImageProvider[] {
  const order = (Deno.env.get('IMAGE_PROVIDERS') ?? 'stability,cloudflare,huggingface')
    .split(',')
    .map((id) => id.trim().toLowerCase())
    .filter(Boolean);
  return order.map((id) => PROVIDERS[id]).filter((p): p is ImageProvider => !!p && p.isConfigured());
}

/** Detects the real format from the file signature (providers differ). */
export function sniffContentType(bytes: Uint8Array): ImageContentType | null {
  const ascii = (from: number, to: number) => String.fromCharCode(...bytes.subarray(from, to));
  if (ascii(0, 4) === 'RIFF' && ascii(8, 12) === 'WEBP') return 'image/webp';
  if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'image/jpeg';
  if (bytes[0] === 0x89 && ascii(1, 4) === 'PNG') return 'image/png';
  return null;
}

export const EXTENSIONS: Record<ImageContentType, string> = {
  'image/webp': 'webp',
  'image/jpeg': 'jpg',
  'image/png': 'png',
};

/** Tries each configured provider in order and returns the first valid image. */
export async function generateImage(brief: ImageBrief): Promise<GeneratedImage> {
  const chain = providerChain();
  if (chain.length === 0)
    throw new HttpError(
      500,
      "Aucun service d'images configuré : ajoutez STABILITY_API_KEY ou CLOUDFLARE_ACCOUNT_ID + CLOUDFLARE_API_TOKEN dans les secrets Supabase",
    );

  const failures: string[] = [];
  for (const provider of chain) {
    try {
      const { bytes, model } = await provider.generate(brief);
      const contentType = sniffContentType(bytes);
      if (!contentType) throw new ImageProviderError(provider.label, null, 'fichier image invalide');
      if (failures.length) console.warn(`Image generated by fallback ${provider.id} after: ${failures.join(' ; ')}`);
      return { bytes, contentType, provider: provider.id, model };
    } catch (error) {
      const reason = error instanceof ImageProviderError ? error.reason : 'erreur inattendue';
      if (!(error instanceof ImageProviderError)) console.error(`${provider.id} crashed`, error);
      failures.push(`${provider.label} : ${reason}`);
    }
  }
  throw new HttpError(
    503,
    `Aucun service d'images n'a pu générer la photo (${failures.join(' · ')}). Réessayez plus tard.`,
  );
}
