/**
 * Text generation with automatic fallback between providers.
 *
 * Providers are tried in order (TEXT_PROVIDERS secret, default
 * "gemini,groq,cloudflare"); those without credentials are skipped. Any
 * failure (overload, quota, refused key, timeout…) moves on to the next one;
 * only when all fail does the Studio receive one clear error listing every reason.
 */
import { HttpError } from './http.ts';
import { cloudflareTextProvider } from './text-providers/cloudflare.ts';
import { ProviderError, type ChatParams, type ChatResult, type TextProvider } from './text-providers/common.ts';
import { geminiProvider } from './text-providers/gemini.ts';
import { groqProvider } from './text-providers/groq.ts';

export type { ChatParams, ChatResult } from './text-providers/common.ts';

const PROVIDERS: Record<string, TextProvider> = {
  gemini: geminiProvider,
  groq: groqProvider,
  cloudflare: cloudflareTextProvider,
};

function providerChain(): TextProvider[] {
  return (Deno.env.get('TEXT_PROVIDERS') ?? 'gemini,groq,cloudflare')
    .split(',')
    .map((id) => PROVIDERS[id.trim().toLowerCase()])
    .filter((p): p is TextProvider => !!p && p.isConfigured());
}

/** Fails fast (before spending quota) when no text provider is configured. */
export function assertTextProviderConfigured(): void {
  if (providerChain().length === 0)
    throw new HttpError(
      500,
      'Aucune IA de rédaction configurée : ajoutez GEMINI_API_KEY (ou GROQ_API_KEY) dans Supabase → Edge Functions → Secrets',
    );
}

/** Asks each configured provider in turn for a JSON object. */
export async function chatJson(params: ChatParams): Promise<ChatResult & { provider: string }> {
  const failures: string[] = [];
  for (const provider of providerChain()) {
    try {
      const result = await provider.chatJson(params);
      if (failures.length) console.warn(`Text generated by fallback ${provider.id} after: ${failures.join(' ; ')}`);
      return { ...result, provider: provider.id };
    } catch (error) {
      if (!(error instanceof ProviderError)) console.error(`${provider.id} crashed`, error);
      failures.push(`${provider.label} : ${error instanceof ProviderError ? error.reason : 'erreur inattendue'}`);
    }
  }
  if (failures.length === 0) assertTextProviderConfigured();
  throw new HttpError(
    503,
    `Aucune IA de rédaction n'a pu répondre (${failures.join(' · ')}). Réessayez dans quelques minutes.`,
  );
}
